apiVersion: v1
kind: Pod
metadata:
  name: api
  labels:
    app: api
spec:
  containers:
    - name: api
      image: api
      ports:
      - containerPort: 5000
      imagePullPolicy: IfNotPresent
